version: '2.2'
services:
  spark-master:
    build: master
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==spark-master"
      - PYSPARK_PYTHON=python3
      - SPARK_HOME=/spark/
    mem_limit: 1G
  spark-worker-1:
    build: worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-worker-1"
    mem_limit: 1G
  spark-worker-2:
    build: worker
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-worker-2"
    mem_limit: 1G
  spark-worker-3:
    build: worker
    container_name: spark-worker-3
    depends_on:
    - spark-master
    ports:
    - "8083:8081"
    environment:
    - "SPARK_MASTER=spark://spark-master:7077"
    - "constraint:node==spark-worker-3"
    mem_limit: 1G